### ISSUE TITLE
Store default configuration in app data directory

### ISSUE THREAD

**Issue by rcdailey** [rcdailey/trash-updater#11]
Right now the default configuration file (`trash.yml`) is expected to sit next to the executable in the same directory. Going forward, this configuration file should be stored in the application data directory where the rest of the files (logs, cache, etc) are stored. This will keep things more consistent with how other data files are structured and allow the executable to be moved around without having to also move the YAML file.

For backward compatibility, the program will still continue to read `trash.yml` if it sits next to the executable. But there will be a precedence established: 

- The config specified by the `--config` option is loaded first (existing behavior)
- If the `--config` option is not present, the file `trash.yml` in the app data directory is loaded (new behavior)
- If not found, `trash.yml` sitting next to the executable is loaded (existing behavior)
- If not found, the application throws an exception and exits (existing behavior)

Furthermore:

The `trash create-config` will drop `trash.yml` in the app data directory going forward instead of right next to the executable.

**Comment by jonathan-bloodworth** [comment]
Hi,

Is there any update on this enhancement? I've just started using the updater app and it would be handy to sync the season pack optional season pack regex as well but not sync the other optional preferences. In the meantime do you think this would be doable with just another release profile for season packs?

**Comment by rcdailey** [comment]
Hi did you perhapse mean to respond to https://github.com/rcdailey/trash-updater/issues/8? If so, no issue. Just want to make sure we're talking about the same thing.

Right now Trash Updater is in maintenance mode because I'm working on a web application to replace it which will have a GUI frontend and be much easier to use. Eventually I do plan to add support for selecting individual optional release proflles to that app.

In the meantime, you are correct. Just manually add the optional release profiles you want to a different release profile. Hopefully they don't change too much and there's not too many to add, so it shouldn't be a huge inconvenience.

**Comment by jonathan-bloodworth** [comment]
Hi, this was for sonarr's release profiles, specifically the [optional season pack rule](https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/#optional-matches-season-packs-use-this-if-you-prefer-season-packs), I worked around it by adding the regex to a third profile and the updater hasn't modified it so all good! Great app btw, looking forward to the new version of the app and sounds great, is it too early to tell if it will be a docker image yet?

**Comment by rcdailey** [comment]
Oh it will definitely be in a docker image. In fact that will be the first platform I release it on and the only one I plan to directly support and test. I just don't have the time to test all possible configurations of how a server can be hosted.

I'm still quite a ways out. I'm dealing with a lot of architectural changes right now. I'll be releasing functionality in increments, so it will be a bit of a "downgrade" from a feature perspective, compared to Trash Updater.

Feel free to keep an eye on it here: https://github.com/rcdailey/recyclarr
