### ISSUE TITLE
Failed to map file.

### ISSUE THREAD

**Issue by Motophan** [rcdailey/trash-updater#14]
Failed to map file. open(/home/systemxd/sonarrtrash/trash) failed with error 13
Failure processing application bundle.
Couldn't memory map the bundle file for reading.
A fatal error occured while processing application bundle

**Comment by rcdailey** [comment]
What is your OS and CPU architecture?

**Comment by rcdailey** [comment]
Closing due to no response from OP.

**Comment by mvanbaak** [comment]
I have the same issue

MacOS Big Sur 11.6
CPU: 2,6 GHz Quad-Core Intel Core i7
trash updator 1.6.3

**Comment by mvanbaak** [comment]
all 1.6.X versions give this on macos
Did not test older releases.

**Comment by mvanbaak** [comment]
```bash
Failed to map file. open(/Users/mvanbaak/Downloads/trash) failed with error 13
Failure processing application bundle.
Couldn't memory map the bundle file for reading.
A fatal error occured while processing application bundle
```

Steps I took:
* Download the latest trash-osx.zip from the releases page
* Unzip: ```unzip trash-osx.zip```
* Gave execute permissions: ```chmod +x ./trash```
* Run the app: ```./trash```
* IGet a dialog: '"trash" cannot be opened because the developer cannot be verified.'"
* Open system preferences -> security and allow the application
* Run the app: ```./trash```
* This gives a dialog about 'run the app or move to trash' and click 'Open'
* Output as given above

**Comment by rcdailey** [comment]
@kid What linux distro are you using? CPU architecture (x86, x64, arm)?

I find this issue really weird. I run this on 64-bit Ubuntu and it works fine. The more information about your systems and hardware I can get, the easier it will be to identify the problem.

**Comment by kid** [comment]
I'm using Arch Linux

I just tested on another machine also running Arch, and there it is working fine, so I'll dig through the package list of both machines to find the difference

Both machines are x64
