### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by Blistex77** [rcdailey/trash-updater#21]
Hi,

I've followed the notes about Linux installation, but I'm still getting the "command not found" error on Raspberry PI 3. Is there any chance the binary could be compiled for it?

Thanks a lot for all the work!

**Comment by rcdailey** [comment]
At the moment, I do not release Trash Updater for ARM platforms. Is there a reason you're running it on a Pi? It would work on a windows, linux, or mac platform as long as it is x64 and not ARM.

I will eventually add support for ARM but not right now. There hasn't been a lot of demand for it. In fact, you are the first to mention it, I think.

**Comment by Blistex77** [comment]
No problem. This PI is my main portal for my homelab, that's the only reason I tried to use it on it, but given the frequency I'll use this tool, I can use it on any other machine (I just did on a Windows 10 and it worked perfectly).

Again, thanks a lot for this amazing work. I loved your guide and this tool is just the cherry on the cake!

**Comment by Soulplayer** [comment]
Just want to let you know I’m also interested in an arm version (64bit)

**Comment by hvalev** [comment]
I am also interested in an arm 64-bit version

**Comment by rcdailey** [comment]
I'm reopening this issue as I do plan to add support for ARM

**Comment by rcdailey** [comment]
As of v1.8.0, ARM64 builds are supported on all platforms and a 32-bit ARM build is available for Linux (mainly for older Raspbian OS). Thanks again everyone for your support.
