### ISSUE TITLE
Getting Started update

### ISSUE THREAD

**Issue by Glasti1** [rcdailey/trash-updater#3]
I think it is good to add some extra information to the [Getting Started](https://github.com/rcdailey/trash-updater#getting-started) page

In the first part explaining the content of `trash.py -h` i would extra information. 

Especially:
[`Profiles`](https://trash-guides.info/Sonarr/) will add the Release Profiles as explained in the guide
Currently you can add the following Release Profiles:

- [web-dl](https://trash-guides.info/Sonarr/V3/Sonarr-Release-Profile-RegEx/) `profile sonarr:web-dl`
- [anime](https://trash-guides.info/Sonarr/V3/Sonarr-Release-Profile-RegEx-Anime/) `profile sonarr:anime`

[`Quality`](https://trash-guides.info/Sonarr/) will add the Quality Definitions as explained in the guide.
Currently you can add the following Quality Definitions:

- [non-anime](https://trash-guides.info/Sonarr/V3/Sonarr-Quality-Settings-File-Size/#sonarr-quality-definitions-anime-work-in-progress) `quality sonarr:non-anime`
- [anime](https://trash-guides.info/Sonarr/V3/Sonarr-Quality-Settings-File-Size/#sonarr-quality-definitions-anime-work-in-progress) `quality sonarr:anime`

_______________________________________________________________________________________________________________________________

**Example on how to run this on Unraid through the `User Scripts` plugin**

Before running this script you will have to install the dependencies explained in [Requirements](https://github.com/rcdailey/trash-updater#requirements)

After this you want to clone this repository to your array through the CLI:

`cd /mnt/user/scripts`

`git clone https://github.com/rcdailey/trash-updater.git`

Then you can create a script looking something like this.
```
#!/bin/bash

cd /mnt/user/scripts/trash-updater/src

# when not using trash.yml **or** having the file in another location
python3 trash.py profile sonarr:anime --base-uri http://192.168.1.*:8989 --api-key XXXXXXXXXXXXXXXXXX
python3 trash.py quality sonarr:anime --config-file /mnt/user/scripts/trash.py

# when using trash.yml located in the /src folder
python3 trash.py profile sonarr:web-dl
python3 trash.py quality sonarr:non-anime
```
_______________________________________________________________________________________________________________________________
A script like this would be able to be run on other system as well? maybe good to make it more generic if so.

I was not able to get the `--config-file` command working but it added it how i think is correct.

Also i linked as much as possible to the guide so it is easier for people to find the pages for reference.

At the moment this is all i can come up with.

p.s. when you cloned the repo locally what command do you run to update it.?

**Comment by Glasti1** [comment]
```Implement hybrid quality definition logic

The hybrid quality is auto-generated and takes values between the anime
and non-anime tables in the following way:

* The lowest minimum and highest maximum between the non-anime and anime
  tables are used as the min/max for each quality in the generated
  hybrid table.
* Only 720/1080 qualities are "combined". Qualities outside of this,
  such as 2160, use the non-anime min/max values.```

**Comment by rcdailey** [comment]
Closing this one out since after the rewrite, documentation has been expanded extensively and also the CLI is completely different now.
