### ISSUE TITLE
Add option to allow dubs for anime

### ISSUE THREAD

**Issue by n8detar** [rcdailey/trash-updater#37]
In the guide under [Must Not Contain](https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx-Anime/#must-not-contain) `dub` releases are included by default meaning dubs aren't downloaded. It would be great to have an option to allow them to be downloaded and optionally be preferred barely above subs.

**Comment by rcdailey** [comment]
Hello,

Thank you for the feature request. After reviewing this a bit, I feel like it's a reasonable idea but unfortunately beyond the scope of what Trash Updater does. Your request is not really doable for a few reasons:

- It requires a lot of fragile assumptions about the structure and contents of the guide. The guide directs you on how to prevent dubs from being prohibited by modifying an existing release profile, but does so in a way that is not easily implemented in my tool.
- Requires me to infer data that doesn't exist. Specifically, the guide has no reference scores for prioritizing dubs over subs.

In general, any time people want a customized version of release profiles from the guide, I recommend they do the following:

1. Temporarily enable that type (in your case: `type: anime`) in their `trash.yml` and sync it once to Sonarr (this will create the baseline release profile from the guide).
2. Remove that type from your `trash.yml` (you will manually update it from now on).
3. Go to the release profile in Sonarr and directly edit it to meet your needs.

In the future, remember that Trash Updater is meant for folks that want what's in the guide verbatim in Sonarr. I do add features to include/exclude certain parts of the guide, but it always takes whatever is included verbatim, without modification for the most part.
