### ISSUE TITLE
Error running script  -  !! Inside bracket with invalid state; skipping!

### ISSUE THREAD

**Issue by bolagnaise** [rcdailey/trash-updater#4]
Trying to run this script, but keep getting the following error i think,

Using configuration file: /mnt/user/MULTIMEDIA/Scripts/trash-updater/src/trash.yml
Config file could not be loaded because it does not exist
Using markdown page: Sonarr-Release-Profile-RegEx-Anime
> Parsing Header [Text: Anime Delete] [Depth: 2]
> Parsing Header [Text: Media Management] [Depth: 2]
> Parsing Header [Text: Suggested naming scheme] [Depth: 3]
> Parsing Header [Text: Anime Episode Format] [Depth: 4]
  - !! Inside bracket with invalid state; skipping! [Profile Name: None] [Category: TermCategory.Preferred] [Score: None] [Line: {Series TitleYear} - S{season:00}E{episode:00} - {absolute:000} - {Episode CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRange]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}] 
> Parsing Header [Text: Series Folder Format] [Depth: 4]
  - !! Inside bracket with invalid state; skipping! [Profile Name: None] [Category: TermCategory.Preferred] [Score: None] [Line: {Series TitleTheYear} [tvdb-{TvdbId}]] 
> Parsing Header [Text: Season Folder Format] [Depth: 4]
  - !! Inside bracket with invalid state; skipping! [Profile Name: None] [Category: TermCategory.Preferred] [Score: None] [Line: Season {season:00}] 
  - !! Inside bracket with invalid state; skipping! [Profile Name: None] [Category: TermCategory.Preferred] [Score: None] [Line: Scene] 
> Parsing Header [Text: Quality Profile] [Depth: 2]
> Parsing Header [Text: Indexers] [Depth: 2]
> Parsing Header [Text: Release Profiles] [Depth: 2]
  - New Profile [Text: Release Profiles]
> Parsing Header [Text: First Release Profile] [Depth: 3]
  - New Profile [Text: First Release Profile]
  - "Include Preferred" found [Value: True] [Line:     **DO** Check mark `Include Preferred when Renaming` on this release profile.]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[500]**]
  - Score [Value: 500]
    + Capture Term [Category: TermCategory.Preferred] [Score: 500] [Strict: False] [Term: /(multi[ ._-]?audio)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[0]**. This is for renames only and why it is at **0**. It is also added in the second profile. This one is to ensure that the preferred words get added.]
  - Score [Value: 0]
    + Capture Term [Category: TermCategory.Preferred] [Score: 0] [Strict: False] [Term: /(dual[ ._-]?audio)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[100]/[-10000]**]
  - Score [Value: 100]
    + Capture Term [Category: TermCategory.Preferred] [Score: 100] [Strict: False] [Term: /(uncut|unrated|uncensored|\b(AT[-_. ]?X)\b)/i]
> Parsing Header [Text: Second Release Profile] [Depth: 3]
  - New Profile [Text: Second Release Profile]
  - "Include Preferred" found [Value: False] [Line:     **DO NOT** Check mark `Include Preferred when Renaming`]
> Parsing Header [Text: Must Not Contain] [Depth: 4]
  - Category Set [Name: TermCategory.Ignored] [Line: #### Must Not Contain]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(\[EMBER\]|-EMBER\b|DaddySubs)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(BDMV|M2TS|\bSSA\b|\bVOSTFR\b|\bAbemaTV\b)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(CuaP|PnPSubs|ICEBLUE|SLAX|U3-Web)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(Raws-Maji|\bKRP\b|M@nI|Kanjouteki|PuyaSubs)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /\b(Beatrice|ohys|Kawaiika|neko|daddy)[ ._-]?(raws)\b/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /\b(LowPower|Scryous)[ ._-]?(raws)\b/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /\b(NS|AREY|BDMV|BDVD|BJX|DKB|DP|TnF)\b/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(Amb3r|DsunS|ExREN|\$tore-Chill)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(\[Hatsuyuki\]|-Hatsuyuki\b|\[Hitoku\]|-Hitoki\b)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(\[Foxtrot\]|-Foxtrot\b|HollowRoxas|\bMGD\b)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(JacobSwaggedUp|KEKMASTERS|\[Mites\]|-Mites\b)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(neoHEVC|Pantsu|\[Pao\]|-Pao\b|Plex Friendly)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(Rando235|RandomRemux|Reaktor|RightShiftBy2)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(\bSHFS\b|StrayGods|\bUQW\b|Yabai_Desu_Ne)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(YakuboEncodes|\b(WtF[ ._-]?Anime)\b)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /((funi|eng(lish)?)_?dub|\bdub(bed)?\b)/i]
    + Capture Term [Category: TermCategory.Ignored] [Term: /(Golumpa|torenter69|KamiFS|KaiDubs)/i]
> Parsing Header [Text: Preferred] [Depth: 4]
  - Category Set [Name: TermCategory.Preferred] [Line: #### Preferred]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[501]**]
  - Score [Value: 501]
    + Capture Term [Category: TermCategory.Preferred] [Score: 501] [Strict: False] [Term: /dual[ ._-]?audio|EN\+JA|JA\+EN/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[100]**]
  - Score [Value: 100]
    + Capture Term [Category: TermCategory.Preferred] [Score: 100] [Strict: False] [Term: /\b(?:(BluRay|Blu-Ray|BDMux|BD(?!$))|(BDRip)|(BRRip))(?:\b|$|[ .])/ix]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[15]**]
  - Score [Value: 15]
    + Capture Term [Category: TermCategory.Preferred] [Score: 15] [Strict: False] [Term: /\b(WEB[-_. ]DL|WEBDL|WebHD|[. ]WEB[. ](?:[xh]26[45]|DDP?5[. ]1)|[. ](?-i:WEB)$|\d+0p(?:WEB-DLMux|\b\s\/\sWEB\s\/\s\b))/ix]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[10]**]
  - Score [Value: 10]
    + Capture Term [Category: TermCategory.Preferred] [Score: 10] [Strict: False] [Term: /(WebRip|Web-Rip|WEBMux)/ix]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[5]**]
  - Score [Value: 5]
    + Capture Term [Category: TermCategory.Preferred] [Score: 5] [Strict: False] [Term: /\b(?:(1080p|1920x1080|1440p|FHD|1080i|4kto1080p))\b/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[4000]**]
  - Score [Value: 4000]
    + Capture Term [Category: TermCategory.Preferred] [Score: 4000] [Strict: False] [Term: /(deanzel|\bZR\b|\bCTR\b|\bSCY\b|\bMK\b|TTGA)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 4000] [Strict: False] [Term: /(\bShir\b|LostYears|BluDragon|KAWAiREMUX)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 4000] [Strict: False] [Term: /(\bAC\b|ShadyCrab|Rasetsu|Raizel|Dragon-Releases)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 4000] [Strict: False] [Term: /(\[Spark\]|-Spark\b|\bREVO\b|\bSRLS\b|ANThELIa)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 4000] [Strict: False] [Term: /(\[Vanilla\]|-Vanilla\b|\bAP\b)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[3750]**]
  - Score [Value: 3750]
    + Capture Term [Category: TermCategory.Preferred] [Score: 3750] [Strict: False] [Term: /(E[.-]N[.-]D)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[3500]**]
  - Score [Value: 3500]
    + Capture Term [Category: TermCategory.Preferred] [Score: 3500] [Strict: False] [Term: /(\bHAiKU\b|Exiled-Destiny|\b(E-D)\b|Koten[ ._-]Gars)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 3500] [Strict: False] [Term: /(\[GHOST\]|-GHOST\b|\[NPC\]|-NPC\b|\bCBM\b)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 3500] [Strict: False] [Term: /(\bKH\b|\bCBT\b|naiyas|ShowY|Kametsu|\bPn8\b|Hark0N)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[3000]**]
  - Score [Value: 3000]
    + Capture Term [Category: TermCategory.Preferred] [Score: 3000] [Strict: False] [Term: /(\bDHD\b|RedBlade|TENEIGHTY|WaLMaRT)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 3000] [Strict: False] [Term: /(\bBMF\b|\[STRiFE\]|-STRiFE\b)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 3000] [Strict: False] [Term: /(MKVULTRA|iAHD|ANiHLS)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[2500]**]
  - Score [Value: 2500]
    + Capture Term [Category: TermCategory.Preferred] [Score: 2500] [Strict: False] [Term: /(\[YURASUKA\]|-YURASUKA\b|karios|Arukoru)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 2500] [Strict: False] [Term: /(\bRH\b|\[Prof\]|-Prof\b)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[2000]**]
  - Score [Value: 2000]
    + Capture Term [Category: TermCategory.Preferred] [Score: 2000] [Strict: False] [Term: /(DragsterPS)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[1500]**]
  - Score [Value: 1500]
    + Capture Term [Category: TermCategory.Preferred] [Score: 1500] [Strict: False] [Term: /(xPearse|\bMCR\b|\bKS\b|KiyoshiStar)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[1000]**]
  - Score [Value: 1000]
    + Capture Term [Category: TermCategory.Preferred] [Score: 1000] [Strict: False] [Term: /(\b(A-L)\b)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[300]**]
  - Score [Value: 300]
    + Capture Term [Category: TermCategory.Preferred] [Score: 300] [Strict: False] [Term: /(Erai-raws|KAN3D2M)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[250]**]
  - Score [Value: 250]
    + Capture Term [Category: TermCategory.Preferred] [Score: 250] [Strict: False] [Term: /(HorribleSubs|SubsPlease|SallySubs)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[200]**]
  - Score [Value: 200]
    + Capture Term [Category: TermCategory.Preferred] [Score: 200] [Strict: False] [Term: /(\[Mysteria\]|-Mysteria\b|Asenshi)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 200] [Strict: False] [Term: /(\[meta\]|-meta\b|BlueLobster)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[150]**]
  - Score [Value: 150]
    + Capture Term [Category: TermCategory.Preferred] [Score: 150] [Strict: False] [Term: /(\bGJM\b|kBaraka)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[100]**]
  - Score [Value: 100]
    + Capture Term [Category: TermCategory.Preferred] [Score: 100] [Strict: False] [Term: /(\bCH\b|\bFFF\b|Licca|Soldado|SNSbu)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 100] [Strict: False] [Term: /(Coalgirls|BlurayDesuYo|DameDesuYo|\bPAS\b)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[50]**]
  - Score [Value: 50]
    + Capture Term [Category: TermCategory.Preferred] [Score: 50] [Strict: False] [Term: /(\[Orphan\]|-Orphan\b|\[Yabai\]|-Yabai\b|\bNii-sama\b)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 50] [Strict: False] [Term: /(\[Doki\]|-Doki\b|\[Chihiro\]|-Chihiro\b|Final8)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: 50] [Strict: False] [Term: /(\[tenshi\]|-tenshi\b|SHiN-gx)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[25]**]
  - Score [Value: 25]
    + Capture Term [Category: TermCategory.Preferred] [Score: 25] [Strict: False] [Term: /(AkihitoSubs|\bASW\b|Commie)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[1]**]
  - Score [Value: 1]
    + Capture Term [Category: TermCategory.Preferred] [Score: 1] [Strict: False] [Term: /(10.?bit|hi10p)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[1]**]
  - Score [Value: 1]
    + Capture Term [Category: TermCategory.Preferred] [Score: 1] [Strict: False] [Term: /\d(v2)\b/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[2]**]
  - Score [Value: 2]
    + Capture Term [Category: TermCategory.Preferred] [Score: 2] [Strict: False] [Term: /\d(v3)\b/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[3]**]
  - Score [Value: 3]
    + Capture Term [Category: TermCategory.Preferred] [Score: 3] [Strict: False] [Term: /\d(v4)\b/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[-10000]**]
  - Score [Value: -10000]
    + Capture Term [Category: TermCategory.Preferred] [Score: -10000] [Strict: False] [Term: /(\[Judas\]|-Judas|\[Cleo\]|-Cleo)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -10000] [Strict: False] [Term: /(AnimeRG|bonkai77|URANiME)/i]
  - Category Set [Name: TermCategory.Preferred] [Line: Add this to your Preferred with a score of **[-15000]**]
  - Score [Value: -15000]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(\[Pixel\]|-Pixel\b\[EDGE\]|-EDGE\b|\[Ranger\]|-Ranger\b)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(SpaceFish|DeadFish|\bDB\b|Man\.K|\bHR\b)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(BakedFish|N[eo][wo]b[ ._-]?Subs|\bAnime Time\b)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(AnimeKaizoku|Kaizoku|\bCBB\b|phazer11)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(iPUNISHER|MiniTheatre|MiniFreeza|Mr\.Deadpool)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(NemDiggers|Project-gxs|youshikibi)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(\bMD\b|Pog42|mdcx)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(A-Destiny|TOPKEK|\bUwU\b|DARKFLiX)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(\[Maximus\]|-Maximus\b|\[224\]|-224\b)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(\[Harunatsu\]|-Harunatsu\b)/i]
    + Capture Term [Category: TermCategory.Preferred] [Score: -15000] [Strict: False] [Term: /(\[Davinci\]|-Davinci\b)/i]
> Parsing Header [Text: Completed] [Depth: 3]
> Parsing Header [Text: Acknowledgements] [Depth: 3]

Creating new profile: [Trash] Anime - First Release Profile
Creating new profile: [Trash] Anime - Second Release Profile`

**Comment by rcdailey** [comment]
What exact command line did you run? Did you check if the file exists here that it told you it is loading (`/mnt/user/MULTIMEDIA/Scripts/trash-updater/src/trash.yml`)? Need more info.

**Comment by rcdailey** [comment]
Closing:

- No response from OP 
- C# rewrite has rendered this issue moot
