### ISSUE TITLE
Yellow text is impossible to read

### ISSUE THREAD

**Issue by newadventure079** [rcdailey/trash-updater#40]
![Screen Shot 2022-03-19 at 12 32 12 AM](https://user-images.githubusercontent.com/84156407/159110341-7177c6b8-022e-4cbe-8874-77525d925a75.jpg)

The teal text isn't much better either

**Comment by rcdailey** [comment]
The colors are designed for a dark background. Try changing your terminal colors, the app should respect those settings. 

In any case there is nothing I plan to do about this for now.
